### PR TITLE
94 bug/gameview merge conflicts

### LINKED ISSUE #94: Gameview merge conflicts
**Describe the bug**
Gameview merged incorrectly, readding and replacing incorrect parts

### PR DESCRIPTION
**Pull request by TeaWithLucas**
## Why is this merge request being submitted?
fixes #94

## What does this merge request add functionality-wise?
start locations fixed to be in the building

## How has the code been tested?
[ ] Automated tests

[x] Manual tests (specify what you've done)
tested the new locations and UI

[ ] New feature (never existed before)

[x] Feature update (enhancing already existing feature)

[ ] Breaking feature (changes the already existing way of how the process works)

### CODE REVIEW

File: Assets/Scripts/Managers/InstanceManager.cs [hunk 1]
```diff
@@ -100,11 +100,11 @@ public static class InstanceManager {
         }
 
         public static GameObject DisplayFullscreen(string name) {
-            return Instantiate(name, Canvas.transform.Find("Fullscreen"));
+            return Instantiate(name, Canvas.transform.Find("Player UI").Find("Fullscreen"));
         }
 
         public static GameObject DisplayWindow(string name) {
-            return Instantiate(name, Canvas.transform.Find("Windows Section"));
+            return Instantiate(name, Canvas.transform.Find("Player UI").Find("View Area").Find("Middle Section").Find("Windows Section"));
```
Comment (Somafet) [inline Assets/Scripts/Managers/InstanceManager.cs:107]: Could we not store a reference for this instead of instantiating it every time?

Comment (TeaWithLucas) [reply Assets/Scripts/Managers/InstanceManager.cs:107]: Do you mean a serialized field?

Comment (Somafet) [reply Assets/Scripts/Managers/InstanceManager.cs:107]: I mean a field in the class for it e.g:

```
GameObject windowsSection;

public static GameObject DisplayWindow(string name) {
    if (windowsSection == null ) { 
        windowsSection = Instantiate(name, Canvas.transform.Find("Player UI").Find("View Area").Find("Middle Section").Find("Windows Section"));
    }

    return windowsSection;
}
````

Comment (TeaWithLucas) [reply Assets/Scripts/Managers/InstanceManager.cs:107]: > 
> 
> I mean a field in the class for it e.g:
> 
> ```
> GameObject windowsSection;
> 
> public static GameObject DisplayWindow(string name) {
>     if (windowsSection == null ) { 
>         windowsSection = Instantiate(name, Canvas.transform.Find("Player UI").Find("View Area").Find("Middle Section").Find("Windows Section"));
>     }
> 
>     return windowsSection;
> }
> ```

Sure, ill implement that now

Comment (Somafet) [reply Assets/Scripts/Managers/InstanceManager.cs:107]: Just another question, is this GameObject then destroyed later?

Comment (TeaWithLucas) [reply Assets/Scripts/Managers/InstanceManager.cs:107]: What GameObject?

Comment (Somafet) [reply Assets/Scripts/Managers/InstanceManager.cs:107]: The return value of `DisplayWindow`

Comment (TeaWithLucas) [reply Assets/Scripts/Managers/InstanceManager.cs]: Depends on the object, so currently, this is currently just used to Instantiate a task, which destroys itself when completed or closed using the X in the top right.

Comment (TeaWithLucas) [reply Assets/Scripts/Managers/InstanceManager.cs]: Also those gameobjects are now referenced on sceneload

File: Assets/Scripts/Managers/InstanceManager.cs [hunk 2]
```diff
@@ -100,11 +109,20 @@ public static class InstanceManager {
...
         }
-
+        
         public static GameObject DisplayWindow(string name) {
-            return Instantiate(name, Canvas.transform.Find("Player UI").Find("View Area").Find("Middle Section").Find("Windows Section"));
+            if (FullScreen) {
+                return Instantiate(name, WindowsSection);
+            } else {
+                return null;
+            }
```
Comment (Somafet) [inline Assets/Scripts/Managers/InstanceManager.cs:125]: I didn't quite mean it like this. The reason I suggested the code bit I posted before was that it stores the Display Window in a variable. By default it's `null` and so the first time the method is called it would Instantiate the GameObject and store the reference for it in a field. Later, since the GameObject is stored in the variable I won't have to be re-instantiated, you can just return the already stored GameObject (thus increasing performace). However, my other question asking whether this GameObject is then destroyed anywhere is important because then this method is a bit more tricky and the destroy part would have to be refactored to only disable the GameObject instead. Let me know if you need any clarifications

Comment (TeaWithLucas) [reply Assets/Scripts/Managers/InstanceManager.cs:125]: You can't do that on a static class, if you referenced the window class then went to the main menu, you would then be referencing a destroyed object, which would cause errors. This way the window gameobject is referenced when the playercanvus prefrab is present on sceneload and is set to null when that prefab isn't. Your method isn't actually quicker, it just stores it on first call, whereas the way I have done it, calls it on sceneload. Does that clear it up?

Comment (Somafet) [reply Assets/Scripts/Managers/InstanceManager.cs:125]: Once destroyed though, the reference should be nullified thus the first case of the if statement would be true again. It's not meant to be quicker it's meant to avoid reinstantiating of the same object and then destroying it over and over

Comment (TeaWithLucas) [reply Assets/Scripts/Managers/InstanceManager.cs:125]: I think we might have crossed wires. Is the object your talking about the "Windows Section" object or the Instantiated task object?
